### ISSUE TITLE
Attmepted docker-compose up on OSX and get lots of ssl errors

### ISSUE THREAD

**Issue by tavdog** [liamcottle/meshtastic-map#88]
Only the DB remains running after compose up command.
```meshtastic-mqtt  | 
meshtastic-mqtt  | PrismaClientInitializationError: Unable to require(`/app/node_modules/.prisma/client/libquery_engine-linux-musl-arm64-openssl-1.1.x.so.node`).
meshtastic-mqtt  | The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
meshtastic-mqtt  | 
meshtastic-mqtt  | Details: Error loading shared library libssl.so.1.1: No such file or directory (needed by /app/node_modules/.prisma/client/libquery_engine-linux-musl-arm64-openssl-1.1.x.so.node)
meshtastic-mqtt  |     at Object.loadLibrary (/app/node_modules/@prisma/client/runtime/library.js:111:10219)
meshtastic-mqtt  |     at async vr.loadEngine (/app/node_modules/@prisma/client/runtime/library.js:112:448)
meshtastic-mqtt  |     at async vr.instantiateLibrary (/app/node_modules/@prisma/client/runtime/library.js:111:12829) {
meshtastic-mqtt  |   clientVersion: '5.16.1',
meshtastic-mqtt  |   errorCode: undefined
meshtastic-mqtt  | }
meshtastic-mqtt  | 
meshtastic-mqtt  | Node.js v22.12.0
meshtastic-map   | Server running at http://127.0.0.1:8080
meshtastic-map   | prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
meshtastic-map   | Please manually install OpenSSL and try installing Prisma again.```

**Comment by tavdog** [comment]
here is the full compose up log https://gist.github.com/tavdog/5e7b14d79455d2e556e68e4191f08315

**Comment by tavdog** [comment]
got it working by modifying Dockerfile to be the following
```FROM node:16-alpine

RUN apk add --no-cache openssl1.1-compat

# add project files to /app
ADD ./ /app
WORKDIR /app

# install node dependencies
RUN npm install

EXPOSE 8080```
